[default]
; Test-Regel: von der Konsole aus die 1001 anrufen und die Welt wird begrüßt
exten => 1001,1,Answer()
exten => 1001,2,Playback(hello-world)
exten => 1001,3,Hangup()

; Itemstatus in openHAB ändern via REST:
exten => <fritzbox-internal-nr>,1,System(curl -X POST --header "Content-Type: text/plain" --header "Accept: application/json" -d "ON" "http://<openhab-host-or-ip>:8080/rest/items/<switch-item>")

