[general]
context=default
bindport=5060
bindaddr=0.0.0.0
srvlookup=yes
progressinband=yes

register=> <voip-username>:<voip-password>@<fritzbox-host-or-ip>/<fritzbox-internal-nr>

[<fritzbox-internal-nr>]
type=peer
username=<voip-username>
fromuser=<voip-username>
secret=<voip-password>
host=<fritzbox-host-or-ip>
fromdomain=<fritzbox-host-or-ip>
canreinvite=no
nat=no
qualify=yes
insecure=port,invite
qualifyfreq=600
